language: elisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ] ; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-lucid emacs-snapshot-el emacs-snapshot ;
    fi
  - if [ "$EMACS" = 'emacs24' ] ; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24-lucid emacs24-el emacs24-common-non-dfsg ;
    fi
script:
  - emacs -q --batch --eval "(setq byte-compile-error-on-warn nil)" -f batch-byte-compile qemu-mode.el
